### ISSUE TITLE
[User can set basemodel when training/inference & support multi controlnet dir/path ]「建议」建议提供自定义底模和ControlNet模型的位置

### ISSUE THREAD

**Issue by LaowangNineTT** [aigc-apps/sd-webui-EasyPhoto#30]
在使用EasyPhoto的时候，建议可以保留入口，把用户基于Lora训练的底模路径填入，这样就不需要从阿里云的oss下载chilloutMix了，而且大部分用户一般接触这个插件，基本上都安装过ControlNet了，也可以在外层保留ControlNet的模型自定义路径，这样也不需要重复去下载模型了，现在把底模和各个ControlNet都下载，既浪费作者的带宽，也浪费用户的存储空间。

**Comment by newstargo** [comment]
我也指定了路径，下载了好几个小时，现在打开还是爆显存，不知如何是好呢

**Comment by bubbliiiing** [comment]
> 在使用EasyPhoto的时候，建议可以保留入口，把用户基于Lora训练的底模路径填入，这样就不需要从阿里云的oss下载chilloutMix了，而且大部分用户一般接触这个插件，基本上都安装过ControlNet了，也可以在外层保留ControlNet的模型自定义路径，这样也不需要重复去下载模型了，现在把底模和各个ControlNet都下载，既浪费作者的带宽，也浪费用户的存储空间。

抱歉，我们其实去检索了controlnet 模型所在的路径，如果没有文件才会开始下载，我们可能不太了解当前用户的情况，现在是一般把这些模型不放在models/ControlNet中吗？

其实这个下载主要是为了方便，因为中间有很多执行流程，为了防止同学们报错。

**Comment by bubbliiiing** [comment]
> 我也指定了路径，下载了好几个小时，现在打开还是爆显存，不知如何是好呢

莫急，我和你一样是两张3060，肯定是能跑通的，我看你之前的报错，我分析下来应该是因为输入图片分辨率非常大，是这样吗？

**Comment by bubbliiiing** [comment]
> 在使用EasyPhoto的时候，建议可以保留入口，把用户基于Lora训练的底模路径填入，这样就不需要从阿里云的oss下载chilloutMix了，而且大部分用户一般接触这个插件，基本上都安装过ControlNet了，也可以在外层保留ControlNet的模型自定义路径，这样也不需要重复去下载模型了，现在把底模和各个ControlNet都下载，既浪费作者的带宽，也浪费用户的存储空间。

自定义底模确实可以考虑开放出来，这个我需要和同事商量一下以怎样的形式。

**Comment by newstargo** [comment]
> > 我也指定了路径，下载了好几个小时，现在打开还是爆显存，不知如何是好呢
> 
> 莫急，我和你一样是两张3060，肯定是能跑通的，我看你之前的报错，我分析下来应该是因为输入图片分辨率非常大，是这样吗？

小图是1944*2592，大图是5184*3880，是要改成512*512吗？

**Comment by bubbliiiing** [comment]
理解了，我们已经知道问题了，其实就是原图太大导致超分爆显存，我们会在下个版本做个更新，如果现在试用的话可以把这行进行注释。

**Comment by newstargo** [comment]
> 理解了，我们已经知道问题了，其实就是原图太大导致超分爆显存，我们会在下个版本做个更新，如果现在试用的话可以把这行进行删除。 https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/main/scripts/preprocess.py 123行开始。
> 
> ```python
> # 根据质量得分、图像大小去判断哪些图片进行codeformer
> if (selected_scores[index] < 0.60 or np.shape(sub_image)[0] < 512 or np.shape(sub_image)[1] < 512) and codeformer_num < max_codeformer_num:
>     sub_image = Image.fromarray(cv2.cvtColor(portrait_enhancement(sub_image)[OutputKeys.OUTPUT_IMG], cv2.COLOR_BGR2RGB))
>     codeformer_num += 1
> ```

torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
C:\Users\nsg\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\train_kohya/train_lora.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-06_23:20:35
  host      : USER-20230706TY
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1204)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-06_23:20:35
  host      : USER-20230706TY
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11724)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Error executing the command: Command '['C:\\Users\\nsg\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'C:\\Users\\nsg\\stable-diffusion-webui\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\111\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\111\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\111\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=111']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\nsg\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\nsg\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\nsg\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\nsg\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\nsg\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\nsg\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\nsg\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\nsg\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 218, in easyphoto_train_forward
    copyfile(best_weight_path, webui_save_path)
  File "C:\Users\nsg\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nsg\\stable-diffusion-webui\\outputs/easyphoto-user-id-infos\\111\\user_weights\\best_outputs/111.safetensors',  删了123行的代码，显存没爆，但提示多卡，就有这问题，我指定了0卡跑的，怎么处理呢

**Comment by bubbliiiing** [comment]
不好i所以，你的启动命令是什么

**Comment by newstargo** [comment]
> 不好意思，你的启动命令是什么

--device-id=0 --xformers --enable-insecure-extension-access  --listen --port 6677

**Comment by bubbliiiing** [comment]
先执行set CUDA_VISIBLE_DEVICES=0

**Comment by newstargo** [comment]
> 先执行set CUDA_VISIBLE_DEVICES=0

谢谢，终于可以跑通了，效果是有点像，如果有参数指引，多炼几个会好些。

**Comment by bubbliiiing** [comment]
> > 先执行set CUDA_VISIBLE_DEVICES=0
> 
> 谢谢，终于可以跑通了，效果是有点像，如果有参数指引，多炼几个会好些。

好，感谢支持，后续还有更多的优化，效果会更好一些，还没有merge hh

**Comment by wuziheng** [comment]
@bubbliiiing @newstargo  
方便梳理一下所有的建议和action，是不是要放到PR20里面合入，然后做一个汇总，等到全部解决后，我们再close这个issue.

**Comment by LaowangNineTT** [comment]
> > 在使用EasyPhoto的时候，建议可以保留入口，把用户基于Lora训练的底模路径填入，这样就不需要从阿里云的oss下载chilloutMix了，而且大部分用户一般接触这个插件，基本上都安装过ControlNet了，也可以在外层保留ControlNet的模型自定义路径，这样也不需要重复去下载模型了，现在把底模和各个ControlNet都下载，既浪费作者的带宽，也浪费用户的存储空间。
> 
> 抱歉，我们其实去检索了controlnet 模型所在的路径，如果没有文件才会开始下载，我们可能不太了解当前用户的情况，现在是一般把这些模型不放在models/ControlNet中吗？
> 
> 其实这个下载主要是为了方便，因为中间有很多执行流程，为了防止同学们报错。

同步一下当前的情况，方便开发者理解

1. 目前底模的存储路径一般是处于 __SD_INSTALL_DIR_\models\Stable-diffusion，没错，但是会出现两个通用问题：
1-1. 一个是用户因为下载模型太多，对各类模型做子文件夹分类，比如 `__SD_INSTALL_DIR_\models\Stable-diffusion\写实` 之类；
1-2. 另外一个原因是大家下载的大模型可能是该模型的其他版本，比如 chilloutMix-Ni 等；

2. ContrlNet 的存储目录大部分位于 __SD_INSTALL_DIR_\extensions\sd-webui-controlnet\models 目录中，并非上述目录。

**Comment by wuziheng** [comment]
@LaowangNineTT  @newstargo  我们试图在这个PR 引入自定义底模，并在测试中发现可以在训练完后直接更换适配新的底模也能有很好的效果 https://github.com/aigc-apps/sd-webui-EasyPhoto/pulls

**Comment by wuziheng** [comment]
![iwEcAqNwbmcDAQTRBdAF0QiABrCjsCVUNhUjAgTucR_egLcAB9MAAAAAsWDC1wgACaJpbQoAC9IAJy-i png_720x720q90](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/11889926/db5c1c3f-f755-4741-b9c5-0f33dfd5f0ea)
![lQLPJwHBI1i9-ZjNBgDNBgCwYchwkFYLLoUE7q1FjcC6AQ_1536_1536 png_720x720q90](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/11889926/ae1df975-0b76-41b6-8b2e-e3745d710109)
这里有两个首页图，我们直接更换了底模，就可以拿到动漫化效果

**Comment by aetherwu** [comment]
> > 在使用EasyPhoto的时候，建议可以保留入口，把用户基于Lora训练的底模路径填入，这样就不需要从阿里云的oss下载chilloutMix了，而且大部分用户一般接触这个插件，基本上都安装过ControlNet了，也可以在外层保留ControlNet的模型自定义路径，这样也不需要重复去下载模型了，现在把底模和各个ControlNet都下载，既浪费作者的带宽，也浪费用户的存储空间。
> 
> 抱歉，我们其实去检索了controlnet 模型所在的路径，如果没有文件才会开始下载，我们可能不太了解当前用户的情况，现在是一般把这些模型不放在models/ControlNet中吗？
> 
> 其实这个下载主要是为了方便，因为中间有很多执行流程，为了防止同学们报错。

我这里默认 ControlNet 模型在 extensions/sd-webui-controlnet/models 下。

**Comment by wuziheng** [comment]
@bubbliiiing  那我们是不是可以添加一个列表，默认去这些路径里面找模型control or base，然后列表让开源同学们不断补充
